export const CHAT_CREATE_APP = 'CHAT_CREATE_APP'
export const CHATLOG_ADD_MESSAGE = 'CHATLOG_ADD_MESSAGE'
export const CHATLOG_ADD_SIGNAL = 'CHATLOG_ADD_SIGNAL'
export const CHATLOG_REMOVE_SIGNAL = 'CHATLOG_REMOVE_SIGNAL'